### PR TITLE
Add support tree-shaking for lodash by using implicit import

### PR DESCRIPTION
**Pull request by osv**
Improve bundle size

Old:

    sql-formatter.js  607 kB
    sql-formatter.min.js  96.6 kB

New:

    sql-formatter.js  102 kB
    sql-formatter.min.js  35.3 kB

### CODE REVIEW

**Comment by ukupat** [comment]
Vau! Amazing work. Thank you, @osv. I will release this ASAP.

**Comment by ukupat** [comment]
@osv https://github.com/zeroturnaround/sql-formatter/releases/tag/v2.1.0 here you go.

**Comment by iamjochem** [comment]
hi there, 

I was about to do a similar PR, great that some one beat me to it :-) 
any chance of a new npm release for this version?

**Comment by ukupat** [comment]
@iamjochem – sorry, I forgot to `npm publish` 🙃  Version 2.1.0 is now published in [NPM](https://www.npmjs.com/package/sql-formatter)

**Comment by iamjochem** [comment]
cheers!

**Pull request merged**
